blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/laranail/env-kit-webui/discussions
    about: Ask questions, share ideas, and get help from the community.
  - name: Documentation
    url: https://opensource.simtabi.com/env-kit-webui/docs/
    about: Read the env-kit-webui documentation.
